#!/usr/bin/env node

/**
 * Dev-server launcher for the multi-deck course.
 *
 * Each lesson is an independent Slidev app on its own port, so cross-deck links in
 * dev point at `localhost:<port>`. That means a deck you navigate *to* has to be
 * running — hence starting several at once.
 *
 * If `mprocs` is installed it drives the processes: one pane per deck, each
 * independently scrollable, startable and restartable. Otherwise the output of
 * every deck is prefixed and interleaved on one stream.
 *
 * Usage:
 *   node scripts/dev.mjs               # hub + all 11 lessons
 *   node scripts/dev.mjs hub           # just the hub
 *   node scripts/dev.mjs 5             # just lesson 5
 *   node scripts/dev.mjs hub 5 6 7     # hub and lessons 5–7
 *   node scripts/dev.mjs 05-arrays     # by slug
 *
 * Flags:
 *   --lazy        only start the hub; start the rest from the mprocs UI (`s`)
 *   --no-mprocs   force the plain prefixed-output launcher
 *
 * Ctrl+C stops every server (`q` in mprocs).
 */

import { spawn, spawnSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import readline from 'node:readline'
import { fileURLToPath } from 'node:url'
import { SLIDEV_BIN, childEnv } from './node-compat.mjs'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')

const registry = JSON.parse(fs.readFileSync(path.join(ROOT, 'common', 'lessons.json'), 'utf8'))

const HUB_PORT = 3030

/** Every runnable deck, in menu order. */
const DECKS = [
  { name: 'hub', dir: path.join(ROOT, 'slides', '00-hub'), port: HUB_PORT, label: 'Lecții (hub)' },
  ...registry.lessons.map(lesson => ({
    name: lesson.slug,
    num: lesson.num,
    dir: path.join(ROOT, 'slides', lesson.slug),
    port: lesson.port,
    label: lesson.title,
  })),
]

// Distinct colours so interleaved output stays readable.
const PALETTE = [36, 32, 33, 35, 34, 91, 92, 93, 95, 94, 96]
const dim = s => `\x1b[2m${s}\x1b[0m`
const bold = s => `\x1b[1m${s}\x1b[0m`

function resolveTargets(args) {
  if (args.length === 0) return DECKS

  const targets = []
  for (const arg of args) {
    const match = DECKS.find(d => d.name === arg || String(d.num) === arg || d.num === Number(arg))
    if (!match) {
      console.error(`\x1b[31m❌ Unknown deck "${arg}".\x1b[0m`)
      console.error(`   Available: ${DECKS.map(d => d.name).join(', ')}`)
      process.exit(1)
    }
    if (!targets.includes(match)) targets.push(match)
  }
  return targets
}

/** Prefix every line of a child's output with its deck name. */
function pipePrefixed(stream, prefix, color) {
  readline.createInterface({ input: stream, crlfDelay: Infinity }).on('line', line => {
    if (line.trim() === '') return
    console.log(`\x1b[${color}m${prefix}\x1b[0m ${line}`)
  })
}

/** The command that serves one deck. */
const deckCommand = deck => [process.execPath, SLIDEV_BIN, 'slides.md', '--port', String(deck.port)]

function hasMprocs() {
  const probe = spawnSync('mprocs', ['--version'], { stdio: 'ignore' })
  return !probe.error && probe.status === 0
}

/**
 * Run the decks under mprocs: one pane per deck in a TUI.
 *
 * The config is generated from the deck list rather than committed, so it can
 * never go stale against common/lessons.json and it honours a subset selection.
 * Values are emitted via JSON.stringify — YAML is a superset of JSON, so that
 * takes care of quoting.
 */
function runWithMprocs(runnable, env, lazy) {
  const procs = runnable
    .map(deck => {
      const autostart = lazy ? deck.name === 'hub' : true
      return [
        `  ${JSON.stringify(`${deck.name} :${deck.port}`)}:`,
        `    cmd: ${JSON.stringify(deckCommand(deck))}`,
        `    cwd: ${JSON.stringify(deck.dir)}`,
        `    autostart: ${autostart}`,
        `    stop: SIGTERM`,
      ].join('\n')
    })
    .join('\n')

  const config = `# Generated by scripts/dev.mjs — do not edit, it is rewritten on every run.
proc_list_width: 30
scrollback: 4000
procs:
${procs}
`

  const configPath = path.join(os.tmpdir(), 'react-native-course-mprocs.yaml')
  fs.writeFileSync(configPath, config, 'utf8')

  const child = spawn('mprocs', ['--config', configPath, '--proc-list-title', 'Prezentări'], {
    stdio: 'inherit',
    env,
  })

  child.on('exit', code => process.exit(code ?? 0))
}

function runPlain(runnable, env) {
  const width = Math.max(...runnable.map(d => d.name.length))
  const children = []
  let shuttingDown = false

  runnable.forEach((deck, index) => {
    const color = PALETTE[index % PALETTE.length]
    const prefix = `[${deck.name.padEnd(width)}]`

    const [bin, ...args] = deckCommand(deck)
    const child = spawn(bin, args, {
      cwd: deck.dir,
      env,
      stdio: ['ignore', 'pipe', 'pipe'],
    })

    pipePrefixed(child.stdout, prefix, color)
    pipePrefixed(child.stderr, prefix, color)

    child.on('exit', code => {
      if (code !== 0 && code !== null && !shuttingDown) {
        console.error(`\x1b[31m${prefix} exited with code ${code}\x1b[0m`)
      }
    })

    children.push(child)
  })

  const shutdown = () => {
    if (shuttingDown) return
    shuttingDown = true
    console.log(`\n${dim('Stopping servers…')}`)
    for (const child of children) child.kill('SIGTERM')
    // Give Vite a moment to close its sockets before we go.
    setTimeout(() => process.exit(0), 500)
  }

  process.on('SIGINT', shutdown)
  process.on('SIGTERM', shutdown)
}

function main() {
  const args = process.argv.slice(2)
  const lazy = args.includes('--lazy')
  const noMprocs = args.includes('--no-mprocs')
  const targets = resolveTargets(args.filter(a => !a.startsWith('--')))

  const missing = targets.filter(d => !fs.existsSync(path.join(d.dir, 'slides.md')))
  for (const deck of missing) {
    console.error(`\x1b[33m⚠️  ${deck.name}: no slides.md — skipped\x1b[0m`)
  }
  const runnable = targets.filter(d => !missing.includes(d))

  if (runnable.length === 0) {
    console.error('\x1b[31m❌ Nothing to run.\x1b[0m')
    process.exit(1)
  }

  const width = Math.max(...runnable.map(d => d.name.length))

  console.log(`\n${bold(`Starting ${runnable.length} presentation server(s)`)}\n`)
  for (const deck of runnable) {
    console.log(`  ${deck.name.padEnd(width)}  http://localhost:${deck.port}/  ${dim(deck.label)}`)
  }
  if (runnable.length > 4) {
    console.log(
      `\n${dim('Each deck is a separate Vite server. Pass names or numbers to start fewer:')}`
    )
    console.log(`${dim('  pnpm dev hub 5 6')}\n`)
  } else {
    console.log('')
  }

  const env = childEnv()

  // mprocs is a TUI: it needs a terminal. Piped output falls back to the plain
  // launcher so `pnpm dev | tee log` and CI-style invocations still work.
  if (!noMprocs && process.stdout.isTTY && hasMprocs()) {
    runWithMprocs(runnable, env, lazy)
    return
  }

  if (lazy) {
    console.log(dim('--lazy needs mprocs; starting everything instead.\n'))
  }

  runPlain(runnable, env)
}

main()
